language: node_js
node_js:
- lts/boron
- node
after_script: bash <(curl -s https://codecov.io/bash)
deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: iAdr0uWFB/zlvCdlbd/d7+zon1K03kiJJTtL/+316c4aP0uOhzBV4+e7fMvb0uTQIwXW1EytkxzoB3FSiSXoLci0m/6EaIz0/Q2p8EftYOmoxG+pRouaTJ4MTBaVVc1alOo1LMRCHS9EDoyRdNhfN61WdpmIc5rFshKEwq31Z/0L7w3KmoKkNGbtu/Mr+EaGus448qgtLb1VO70X2+OfLMbwHXQHhRQh4pyRIjYSBSNWcHR86MypCQsZVaTDWbzfqkpJmYIYwDuUSu3Eww0ygjGdks9Kbp+p4maGAXg+n6GS+gk2F75n2MHbOvXabWiIwuwR15rgZfIr5wpNfzS6PU42VGn5PbJDxtlx/gCeRIKHTnAfIyy8C2HigIX9AG/TnIMDP5VLYoVieHz7VVOLDi4J/DwaeA7xCYD9Du+pOpbTm9zkMu0V9kDRT1eLENo6fTF2pXavL1heGJPHX5OJhA2Of8bwjSeY3vFISm8OOQov+NXJ74dZ6pLIUAs3tJisq2/hOCcMlE5JXOPO1b2x7F8lXEpQ8YUSVPziQGPmBDhDY9czpf32Pmqo32Bd1jCUagIth6azu7IAw+FZek8sWs6Oy10+BsYC2bx3/O8qlzrF/LBoKNjwf02YtQadEFMoJDMVNgUWWNLTr5dz+jaYOchEIJdQucsZYpFYyx+KWzU=
  file:
    - "hast-util-transparent.js"
    - "hast-util-transparent.min.js"
  on:
    tags: true
